### ISSUE TITLE
Bug in retrieving user photo

### ISSUE THREAD

**Issue by rossknudsen** [microsoftgraph/msgraph-training-aspnet-core#10]
https://github.com/microsoftgraph/msgraph-training-aspnet-core/blob/ffb9ed93a1db10df76e598a1d602443f43945575/demo/GraphTutorial/Startup.cs#L90

I had to adjust this line as follows

```cs
if (ex.IsMatch("ErrorItemNotFound") || ex.IsMatch("ConsumerPhotoIsNotSupported"))
```

**Comment by jasonjoh** [comment]
Thanks @rossknudsen for reporting.
