### ISSUE TITLE
The packages specified are different in the command and description.

### ISSUE THREAD

**Issue by Takas0522** [microsoftgraph/msgraph-training-aspnet-core#15]
**Where did you get the code?**
- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
The packages specified in "Add NuGet packages" are different in the command and description.

**To Reproduce**
https://docs.microsoft.com/en-us/graph/tutorials/aspnet-core?tutorial-step=1
The packages specified in "Add NuGet packages" are different in the command and description.

**Expected behavior**
❌dotnet add package Microsoft.Identity.MicrosoftGraph --version 1.1.0
⭕dotnet add package Microsoft.Identity.Web.MicrosoftGraph --version 1.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/22936439/97771767-ace0a000-1b83-11eb-9150-dd06c596753e.png)

**Desktop (please complete the following information):**
- OS Windows10(2004)
- Browser Edge
- Version 86.0.622.56(64bit)

**Dependency versions**

**Additional context**

**Comment by jasonjoh** [comment]
Thanks for reporting.

**Comment by dend** [comment]
@jasonjoh I will add that in the current tutorial there is an error - given the current package configuration, I am unable to use `.AddMicrosoftGraph`, which stems from the problem that @Takas0522 reported. Now that 1.3 is out, can the instructions be updated as well?
