### ISSUE TITLE
Not able to Signin to application using Personal(outlook) Account

### ISSUE THREAD

**Issue by UShehzad** [microsoftgraph/msgraph-training-aspnet-core#21]
**Where did you get the code?**
- [ ] Downloaded from GitHub
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
First Of all thankyou for such great implementation. I am able to login to this application using my Company account (ushehzad@cinnova.com) but unfortunately when I try using my personal account it gives me some error like "The size of the request headers is too long". I digged a little into this issue and found that during this process around 5 cookies are being created with a quiet large size and in various chunks. I tried increasing the request or header size using the web.config but the issue still persists. I am new to such things so a little help will be appreciated. 

**To Reproduce**
Just Login to the application using your personal Microsoft Account.

**Expected behavior**
It Should Login to application and get User Info.

**Screenshots**
![image](https://user-images.githubusercontent.com/93992024/140938882-3f3ce495-68b9-4fc3-aaa6-b7520729f1aa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome, Opera

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:

**Comment by jasonjoh** [comment]
@UShehzad sorry you're having this trouble. Unfortunately I don't hit this error with my personal MS account. In my case the `.AspNetCore.Cookies` is split into two chunks.

One thing that could be causing this is the additional data that the app adds to the user's `ClaimPrincipal`. Specifically, the user photo. If you comment out this line, does it help?

https://github.com/microsoftgraph/msgraph-training-aspnet-core/blob/8ee8dfaa369b99531975e08e932655748cca6507/demo/GraphTutorial/Startup.cs#L79

**Comment by UShehzad** [comment]
@jasonjoh Yes I commented that and now I am able to Login to the application moreover I explored a little and found that it was due to size of image quite large in case of personal account.  I tried to increase the size of Cookie using the web.config but that doesn't work and now I am thinking of trying Session or Redis for such things.

**Comment by UShehzad** [comment]
Hi Jason,
Thank you for responding back to me.  Yes, I commented that, and now I am able to Login to the application moreover I explored a little and found that it was due to the size of the image being quite large in the case of a personal account. I tried to increase the size of Cookie using the web.config but that doesn't work and now I am thinking of trying Session or Redis for such things.





[cid:ff81b07e-51ee-4feb-9c51-21b35acef765]

Umair Shehzad | Software Engineer

Cinnova Technologies, LLC.

92.321.5606105 (direct) | 042.35456733 (office)

www.cinnova.com<https://www.cinnova.com/> | ***@***.******@***.***>

**Comment by jasonjoh** [comment]
Thanks for confirming. I wouldn't expect the file to be that large, as the app requests a 48x48 pixel version of the photo. For my personal account, this results in a 1.4KB JPEG file. However, I think you're heading in the right direction - storing the photo as a data URI in the claim principal is probably not the best approach for "real" apps. Session storage or local storage might be better.
