### ISSUE TITLE
Using Microsoft Graph Beta Endpoint

### ISSUE THREAD

**Issue by Uwe82** [microsoftgraph/msgraph-training-aspnet-core#22]
Hi,
I'm working on a project that needs to use the Microsoft Graph Beta Endpoint (for Workspaces in EXO). Using this sample, I implemented the base code and found a problem:

When I switch the package from Microsoft.Identity.Web.MicrosoftGraph to Microsoft.Identity.Web.MicrosoftGraphBeta the Beta endpoint and code should be used, correct?

Unfortunately the Base URL is changing between Startup code and controller code.

To reproduce: Switch the mentioned package. When you inspect the _graphClient object in Startup.cs, the baseUrl says "https://graph.microsoft.com/beta". When you inspect the _graphClient object in the Calendar Controller (e.g. in the constructor), the baseUrl property is "https://graph.microsoft.com/v1.0".

Can someone explain this to me and give me a workaround?

Thanks in advance,

Uwe

**Comment by jasonjoh** [comment]
This looks like a deliberate design choice in the Microsoft.Identity.Web.MicrosoftGraphBeta package. They seem to default to the v1 endpoint even if you're using the Beta SDK. (See https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphOptions.cs).

Thankfully they expose it in the options, so you can override it. In Startup.cs you'd just set the `BaseUrl` during the call to `AddMicrosoftGraph`.

```csharp
.AddMicrosoftGraph(options => {
    options.Scopes = string.Join(' ', GraphConstants.Scopes);
    options.BaseUrl = "https://graph.microsoft.com/beta";
})
```

**Comment by Uwe82** [comment]
Thanks Jason, this is working! Sometimes a bit overwhelmed by the amount of configuration options ;).
