### ISSUE TITLE
Tutorial Uses Out of Date Microsoft.Identity.Web Package

### ISSUE THREAD

**Issue by adagioajanes** [microsoftgraph/msgraph-training-aspnet-core#4]
When going through this tutorial, it uses a version of Microsoft.Identity.Web that is several revisions behind the current package. Running the tutorial with updated packages is not working. Can this be updated to have instructions for the latest packages?

**Comment by jasonjoh** [comment]
@adagioajanes hopefully this fix should get you going with the 0.3.0-preview version. After you upgrade, you might still see the empty login partial if you still have cookies in your browser. If that's the case, sign out, then sign back in.
