### ISSUE TITLE
Events with previous week start date and this week end date displayed incorrectly

### ISSUE THREAD

**Issue by VladilenK** [microsoftgraph/msgraph-training-aspnet-core#7]
**Where did you get the code?**
- [x] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
If the event starts previous week and ends this week - it will be displayed incorrectly (under the wrong day of week).

**To Reproduce**
1. Create an event in calendar that starts previous week and ends this week
2. Go to the Calendar in the menu.

**Expected behavior**
An event is not displayed or displayed under the day it ends.

**Screenshots**
![image](https://user-images.githubusercontent.com/32023073/93139029-ab2b4d80-f6a5-11ea-88a9-1974860feaf1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro N build 19041
 - Browser: Chrome
 - Version: 85

** Suspected cause and proposed solution **
suspected cause: 
```
        private IEnumerable<CalendarViewEvent> GetEventsForDay(System.DayOfWeek day)
        {
            return _events.Where(e => e.Start.DayOfWeek.Equals(day));
        }
```
proposed solution: 
```
       private IEnumerable<CalendarViewEvent> GetEventsForDay(System.DayOfWeek day)
        {
            return _events.Where(e => ((e.Start.DayOfWeek.Equals(day)) & (e.Start.Date >= _startOfWeek)) | ((e.End.DayOfWeek.Equals(day)) & (e.Start.Date < _startOfWeek)));
        }
 
```

![image](https://user-images.githubusercontent.com/32023073/93140499-2db50c80-f6a8-11ea-992c-235655c856bd.png)

**Comment by jasonjoh** [comment]
Thanks for reporting this! You're right - this is one of the dangers of trying to create a calendar UI yourself :D. I took a pretty simplistic approach. I'll take a look at how this can be improved. Your solution is definitely better, but I'm not sure having the entry show up only on the day it ends is right either (your 9/10 - 9/17 event). Arguably it should span days, but that adds complexity to the UI that's not really the point of the sample.
