### ISSUE TITLE
Limit access to AD (guest) users only

### ISSUE THREAD

**Issue by jaoord** [microsoftgraph/msgraph-training-aspnet-core#8]
Currently, any user can authenticate against the app, whether they are in my AD or not. How do I limit access to only the users that are in my AD? It doesn't matter if they are guest users or my own AD users.

**Comment by jasonjoh** [comment]
Two things:

- When registering the app, select "Accounts in this organizational directory only"
- Set `TenantId` in appsettings.json to your tenant ID.

**Comment by jaoord** [comment]
Thanks. The only thing is that this will cause errors with the example code, since the guest user won't have a mailbox, but I'll have to figure out a way to work around that.
