### ISSUE TITLE
How to get sites for guest users?

### ISSUE THREAD

**Issue by jaoord** [microsoftgraph/msgraph-training-aspnet-core#9]
I couldn't find this anywhere in the documentation. I'm using the dotnet core sdk, and I can get the sharepoint sites for an AD member with `var sites = await _graphClient.Sites.Request().GetAsync();`.

However, this same code does not return anything for a guest AD user (added as guest to the AD). The guest user (an outlook.com user) has been invited (and can access) the sharepoint site, but the site is not returned in the query above.

I made sure that the tenant ID has been switched from common to the specific ID in Azure. I was following the tutorial published here: https://docs.microsoft.com/en-us/graph/tutorials/aspnet-core and expanded on that. The tutorial itself is actually pretty good. It would be nice to have some advanced stuff covered as well.

**Comment by jasonjoh** [comment]
I don't know the answer to your question, and we're not set up to provide general "how-to" support in the tutorial repos. There are at least some limitations (see https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#user-and-group-search-limitations-for-guest-users-in-organizations) but I don't know if you're supposed to be able to query SP sites as a guest.
